cwlVersion: v1.1
class: CommandLineTool
baseCommand: [gatk4, GetSampleName]

label: Run GATK GetSampleName command to get the name of a sample.

doc: |-
  Emits a single sample name from the bam header into an output file. The sample
  name is that in the read group (RG) sample (SM) field.

requirements:
  ShellCommandRequirement: {}
  InlineJavascriptRequirement: {}

hints:
  DockerRequirement:
    dockerPull: demichelislab/gatk4:latest

inputs:
  bam_file:
    doc: The BAM file from which to extract the name.
    type: File
    secondaryFiles: [^.bai, .bai]
    inputBinding:
      prefix: "--input"
  log_to_file:
    doc: |-
      If true, the output generated by the tool will be redirected to a file.
      Otherwise the output will be printed on the output.
    type: boolean
    default: true
  redirect_stdout_to_stderr:
    doc: |-
      If true, includes the stderr output along with the stdout in the log file.
    type: boolean
    default: true
  log_filename:
    doc: The name of the output file that will contain the output.
    type: string
    default: "gatk_sample_name.log"

arguments:
  - valueFrom: "output.txt"
    prefix: "--output"
  - valueFrom: "$(inputs.log_to_file ? '2> ' + inputs.log_filename + (inputs.redirect_stdout_to_stderr ? ' 1>&2' : '') : '')"
    shellQuote: false
    position: 99999

outputs:
  output:
    doc: The name of the sample.
    type: string?
    outputBinding:
      glob: "output.txt"
      loadContents: true
      outputEval: $(self[0].contents)
  log_file:
    doc: The log file, if enabled, that capture the output produced by the tool.
    type: File?
    outputBinding:
      glob: $(inputs.log_filename)
