cwlVersion: v1.1
class: CommandLineTool
baseCommand: [samtools, index]

label: Creates index for BAM files

doc: |-
  Indexes a coordinate-sorted BGZIP-compressed SAM, BAM or CRAM file for fast
  random access.

requirements:
  ShellCommandRequirement: {}
  InlineJavascriptRequirement: {}

hints:
  DockerRequirement:
    dockerPull: demichelislab/samtools:latest

inputs:
  bam_file:
    doc: The BAM file for which an index will be generated.
    type: File
    inputBinding:
      position: 0
  log_to_file:
    doc: |-
      If true, the output generated by the tool will be redirected to a file.
      Otherwise the output will be printed on the output.
    type: boolean
    default: true
  redirect_stdout_to_stderr:
    doc: |-
      If true, it includes the stderr output along with the stdout in the log
      file.
    type: boolean
    default: true
  log_filename:
    doc: The name of the output file that will contain the output.
    type: string
    default: "samtools.log"

arguments:
-   valueFrom: "$(inputs.bam_file.nameroot).bai"
    position: 1
-   valueFrom: "$(inputs.log_to_file ? '2> ' + inputs.log_filename + (inputs.redirect_stdout_to_stderr ? ' 1>&2' : '') : '')"
    shellQuote: false
    position: 99999

outputs:
  bai_file:
    doc: The newly generated index of the BAM file.
    type: File?
    outputBinding:
      glob: "*.bai"
  log_file:
    doc: |-
      The log file, if enabled, that captures the output produced by the tool.
    type: File?
    outputBinding:
      glob: $(inputs.log_filename)
